# Generated by Django 4.2 on 2023-04-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
    ]
